# This is a test workflow.

name: Tester

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ ftenchini-ci ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  execute-test:
    runs-on: [self-hosted, linux, x64]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          lfs: 'true'

      - name: setup kerberos
        run: |
          kinit -kt ~/private/.keytab cmsmwbot@CERN.CH
          klist -k -t -e ~/private/.keytab
          klist
          echo "xrdfs root://eosuser.cern.ch// ls $EOS_DIR"
          xrdfs root://eosuser.cern.ch// ls $EOS_DIR
